"""add fingerprint_version

Revision ID: 6129e531bdd1
Revises: fa7f513eeb02
Create Date: 2026-07-12 21:35:38.771356+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "6129e531bdd1"
down_revision: str | None = "fa7f513eeb02"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "trades",
        sa.Column("fingerprint_version", sa.String(length=8), server_default="oa1", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("trades", "fingerprint_version")
    # ### end Alembic commands ###
