"""create trades and import_batches

Revision ID: fa7f513eeb02
Revises:
Create Date: 2026-07-12 19:33:10.467755+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "fa7f513eeb02"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "import_batches",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("filename", sa.Text(), nullable=False),
        sa.Column("file_sha256", sa.String(length=64), nullable=False),
        sa.Column("rows_received", sa.Integer(), nullable=False),
        sa.Column("rows_accepted", sa.Integer(), nullable=False),
        sa.Column("rows_rejected", sa.Integer(), nullable=False),
        sa.Column("rows_duplicate", sa.Integer(), nullable=False),
        sa.Column("warnings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_import_batches_file_sha256", "import_batches", ["file_sha256"], unique=False
    )
    op.create_table(
        "trades",
        sa.Column("trade_id", sa.UUID(), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("import_batch_id", sa.BigInteger(), nullable=True),
        sa.Column("strategy_family", sa.String(length=128), nullable=True),
        sa.Column("strategy_name", sa.String(length=256), nullable=True),
        sa.Column("strategy_version", sa.String(length=64), nullable=True),
        sa.Column("bot_name", sa.String(length=256), nullable=True),
        sa.Column("environment", sa.String(length=16), nullable=False),
        sa.Column("asset_class", sa.String(length=32), nullable=False),
        sa.Column("instrument_type", sa.String(length=32), nullable=False),
        sa.Column("underlying_symbol", sa.String(length=32), nullable=False),
        sa.Column("contract_description", sa.Text(), nullable=True),
        sa.Column("direction", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("opened_at", sa.DateTime(), nullable=True),
        sa.Column("closed_at", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("dte_at_entry", sa.Integer(), nullable=True),
        sa.Column("days_in_trade", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("entry_price", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("exit_price", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("premium", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("risk", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("realized_pnl", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("return_pct", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("return_on_risk", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("mfe_pct", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("mae_pct", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("mfe_at", sa.DateTime(), nullable=True),
        sa.Column("mae_at", sa.DateTime(), nullable=True),
        sa.Column("underlying_entry_price", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("underlying_exit_price", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("timeframe", sa.String(length=32), nullable=True),
        sa.Column("target_delta", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column("dte_setting", sa.Integer(), nullable=True),
        sa.Column("contract_count_setting", sa.Integer(), nullable=True),
        sa.Column("parse_sources", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tags", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["import_batch_id"], ["import_batches.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("trade_id"),
    )
    op.create_index(op.f("ix_trades_bot_name"), "trades", ["bot_name"], unique=False)
    op.create_index("ix_trades_bot_opened", "trades", ["bot_name", "opened_at"], unique=False)
    op.create_index(op.f("ix_trades_fingerprint"), "trades", ["fingerprint"], unique=True)
    op.create_index(op.f("ix_trades_opened_at"), "trades", ["opened_at"], unique=False)
    op.create_index("ix_trades_strategy_family", "trades", ["strategy_family"], unique=False)
    op.create_index(
        op.f("ix_trades_underlying_symbol"), "trades", ["underlying_symbol"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_trades_underlying_symbol"), table_name="trades")
    op.drop_index("ix_trades_strategy_family", table_name="trades")
    op.drop_index(op.f("ix_trades_opened_at"), table_name="trades")
    op.drop_index(op.f("ix_trades_fingerprint"), table_name="trades")
    op.drop_index("ix_trades_bot_opened", table_name="trades")
    op.drop_index(op.f("ix_trades_bot_name"), table_name="trades")
    op.drop_table("trades")
    op.drop_index("ix_import_batches_file_sha256", table_name="import_batches")
    op.drop_table("import_batches")
    # ### end Alembic commands ###
